#Variables for pr003 (DHCP Server)
---
rhbase_firewall_allow_services:
  - dhcp
dhcp_global_default_lease_time: 14400
dhcp_global_max_lease_time: 14400
dhcp_global_subnet_make: 255.255.0.0
dhcp_global_domain_name: avalon.lan
dhcp_global_domain_name_servers:
      - 172.16.255.254
dhcp_global_routers: 172.16.255.254
dhcp_subnets:
  - ip: 172.16.0.0
    netmask: 255.255.0.0
    routers: 172.16.255.254
    pools:
      - range_begin: 172.16.0.2
        range_end: 172.16.127.254
      - range_begin: 172.16.128.1
        range_end: 172.16.191.254
dhcp_hosts:
  - name: ws0001
    mac: '08:00:27:6E:3A:2C'
    ip: 172.16.128.2
